### ISSUE TITLE
汉化之后好像没有发布软件吧

### ISSUE THREAD

**Issue by 773146535** [Half1900/AlphaClicker#1]
大佬什么时候发布

**Comment by Half1900** [comment]
已经补发上去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月25日(周六) 下午2:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Half1900/AlphaClicker] 汉化之后好像没有发布软件吧 (Issue #1)




 
大佬什么时候发布
